// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WolvesvilleManager.Infrastructure.Persistence;

#nullable disable

namespace WolvesvilleManager.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260708013038_AddExternalCronJobIds")]
    partial class AddExternalCronJobIds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WolvesvilleManager.Domain.Entities.ClanRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClanId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ClanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClanTag")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProtectedApiKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClanId")
                        .IsUnique();

                    b.ToTable("ClanRegistrations");
                });

            modelBuilder.Entity("WolvesvilleManager.Domain.Entities.MemberXpSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClanRegistrationId")
                        .HasColumnType("int");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("TakenAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("Xp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClanRegistrationId", "TakenAtUtc");

                    b.ToTable("MemberXpSnapshots");
                });

            modelBuilder.Entity("WolvesvilleManager.Domain.Entities.ScheduledTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClanRegistrationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<int?>("ExternalRunJobId")
                        .HasColumnType("int");

                    b.Property<int?>("ExternalWarmupJobId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastRunAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("MinVotes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NextRunAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClanRegistrationId");

                    b.HasIndex("Enabled", "NextRunAtUtc");

                    b.ToTable("ScheduledTasks");
                });

            modelBuilder.Entity("WolvesvilleManager.Domain.Entities.TaskExecutionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("RanAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ScheduledTaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledTaskId", "RanAtUtc");

                    b.ToTable("TaskExecutionLogs");
                });

            modelBuilder.Entity("WolvesvilleManager.Domain.Entities.MemberXpSnapshot", b =>
                {
                    b.HasOne("WolvesvilleManager.Domain.Entities.ClanRegistration", "ClanRegistration")
                        .WithMany()
                        .HasForeignKey("ClanRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClanRegistration");
                });

            modelBuilder.Entity("WolvesvilleManager.Domain.Entities.ScheduledTask", b =>
                {
                    b.HasOne("WolvesvilleManager.Domain.Entities.ClanRegistration", "ClanRegistration")
                        .WithMany("ScheduledTasks")
                        .HasForeignKey("ClanRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClanRegistration");
                });

            modelBuilder.Entity("WolvesvilleManager.Domain.Entities.TaskExecutionLog", b =>
                {
                    b.HasOne("WolvesvilleManager.Domain.Entities.ScheduledTask", "ScheduledTask")
                        .WithMany("ExecutionLogs")
                        .HasForeignKey("ScheduledTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduledTask");
                });

            modelBuilder.Entity("WolvesvilleManager.Domain.Entities.ClanRegistration", b =>
                {
                    b.Navigation("ScheduledTasks");
                });

            modelBuilder.Entity("WolvesvilleManager.Domain.Entities.ScheduledTask", b =>
                {
                    b.Navigation("ExecutionLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
