// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WolvesvilleManager.Infrastructure.Persistence;

#nullable disable

namespace WolvesvilleManager.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260730000000_AddWelcomeCheckDiagnostics")]
    partial class AddWelcomeCheckDiagnostics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WolvesvilleManager.Domain.Entities.ClanRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClanId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ClanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClanTag")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastWelcomeCheckAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastWelcomeCheckResult")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("LastWelcomedJoinAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PollExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PollLastClaimedWindowEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PollToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PollWindowsTimeZoneId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ProtectedApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("WelcomeMessageEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("WelcomeMessageTemplate")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("WelcomePingJobId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("WelcomeSendTime1")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("WelcomeSendTime2")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("ClanId")
                        .IsUnique();

                    b.HasIndex("PollToken")
                        .IsUnique();

                    b.ToTable("ClanRegistrations");
                });

            modelBuilder.Entity("WolvesvilleManager.Domain.Entities.MemberXpSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClanRegistrationId")
                        .HasColumnType("integer");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("TakenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("Xp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClanRegistrationId", "TakenAtUtc");

                    b.ToTable("MemberXpSnapshots");
                });

            modelBuilder.Entity("WolvesvilleManager.Domain.Entities.PollHiddenQuest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClanRegistrationId")
                        .HasColumnType("integer");

                    b.Property<string>("QuestKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("ClanRegistrationId", "QuestKey")
                        .IsUnique();

                    b.ToTable("PollHiddenQuests");
                });

            modelBuilder.Entity("WolvesvilleManager.Domain.Entities.PollWindow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClanRegistrationId")
                        .HasColumnType("integer");

                    b.Property<DayOfWeek>("EndDayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<DayOfWeek>("StartDayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("ClanRegistrationId");

                    b.ToTable("PollWindows");
                });

            modelBuilder.Entity("WolvesvilleManager.Domain.Entities.QuestPollResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ClanRegistrationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QuestName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Votes")
                        .HasColumnType("integer");

                    b.Property<bool>("WasShuffle")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ClanRegistrationId", "DecidedAtUtc");

                    b.ToTable("QuestPollResults");
                });

            modelBuilder.Entity("WolvesvilleManager.Domain.Entities.QuestPollVote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ClanRegistrationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("QuestId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClanRegistrationId", "Nickname")
                        .IsUnique();

                    b.ToTable("QuestPollVotes");
                });

            modelBuilder.Entity("WolvesvilleManager.Domain.Entities.ScheduledTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AutoRetryMaxAttempts")
                        .HasColumnType("integer");

                    b.Property<bool>("AutoRetryOnXpNotReached")
                        .HasColumnType("boolean");

                    b.Property<int>("ClanRegistrationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<int?>("ExternalRunJobId")
                        .HasColumnType("integer");

                    b.Property<int?>("ExternalWarmupJobId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastRunAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MinVotes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NextRunAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TargetQuestId")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("TargetQuestName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("TargetQuestPromoImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClanRegistrationId");

                    b.HasIndex("Enabled", "NextRunAtUtc");

                    b.ToTable("ScheduledTasks");
                });

            modelBuilder.Entity("WolvesvilleManager.Domain.Entities.TaskExecutionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("RanAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ScheduledTaskId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledTaskId", "RanAtUtc");

                    b.ToTable("TaskExecutionLogs");
                });

            modelBuilder.Entity("WolvesvilleManager.Domain.Entities.MemberXpSnapshot", b =>
                {
                    b.HasOne("WolvesvilleManager.Domain.Entities.ClanRegistration", "ClanRegistration")
                        .WithMany()
                        .HasForeignKey("ClanRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClanRegistration");
                });

            modelBuilder.Entity("WolvesvilleManager.Domain.Entities.PollHiddenQuest", b =>
                {
                    b.HasOne("WolvesvilleManager.Domain.Entities.ClanRegistration", "ClanRegistration")
                        .WithMany("PollHiddenQuests")
                        .HasForeignKey("ClanRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClanRegistration");
                });

            modelBuilder.Entity("WolvesvilleManager.Domain.Entities.PollWindow", b =>
                {
                    b.HasOne("WolvesvilleManager.Domain.Entities.ClanRegistration", "ClanRegistration")
                        .WithMany("PollWindows")
                        .HasForeignKey("ClanRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClanRegistration");
                });

            modelBuilder.Entity("WolvesvilleManager.Domain.Entities.QuestPollResult", b =>
                {
                    b.HasOne("WolvesvilleManager.Domain.Entities.ClanRegistration", "ClanRegistration")
                        .WithMany()
                        .HasForeignKey("ClanRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClanRegistration");
                });

            modelBuilder.Entity("WolvesvilleManager.Domain.Entities.QuestPollVote", b =>
                {
                    b.HasOne("WolvesvilleManager.Domain.Entities.ClanRegistration", "ClanRegistration")
                        .WithMany()
                        .HasForeignKey("ClanRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClanRegistration");
                });

            modelBuilder.Entity("WolvesvilleManager.Domain.Entities.ScheduledTask", b =>
                {
                    b.HasOne("WolvesvilleManager.Domain.Entities.ClanRegistration", "ClanRegistration")
                        .WithMany("ScheduledTasks")
                        .HasForeignKey("ClanRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClanRegistration");
                });

            modelBuilder.Entity("WolvesvilleManager.Domain.Entities.TaskExecutionLog", b =>
                {
                    b.HasOne("WolvesvilleManager.Domain.Entities.ScheduledTask", "ScheduledTask")
                        .WithMany("ExecutionLogs")
                        .HasForeignKey("ScheduledTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduledTask");
                });

            modelBuilder.Entity("WolvesvilleManager.Domain.Entities.ClanRegistration", b =>
                {
                    b.Navigation("PollHiddenQuests");

                    b.Navigation("PollWindows");

                    b.Navigation("ScheduledTasks");
                });

            modelBuilder.Entity("WolvesvilleManager.Domain.Entities.ScheduledTask", b =>
                {
                    b.Navigation("ExecutionLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
